# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 559083b4ceb424f004247c3902b32c6787bbeac0a38c12bdd5b7254ce60aee234dff93d90aad8bed00b81338499945e4b73ad62cbd539d0e9b080bd8f50ec462

test:
  secret_key_base: 23c13b17c0a26858d168968af1554d65fdd579b2acf3a299305f1bad0c861f4c4b5ed7cc0a48542e090a280e0bb55276837d22c13e33194d2f356902a5fcf766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
